### PR TITLE
Trigger fileinfo reset on keyfile change. Closes #845

### LINKED ISSUE #845: Key file not cleared on click
**Summary**
KeeWeb doesn't clear the key file when clicking on it's name. It should clear it since it disappears when I click on it and thus implies to be cleared.

**Steps to reproduce**
1. Start KeeWeb and create a database which requires a keyfile
2. Save the database
3. Lock the database, select the keyfile, then unlock the database
4. Go to the database's settings
5. Under "Key file" select "Don't use key file"
6. Save and lock the database
7. Select the database
8. Click on the key file to "clear" it and enter the password
9. Now it's not possible to open the database anymore without removing it first and adding it again

**App information**
```
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36
```

**Other information**
OS: Debian 9 with Gnome 3.22.2

### PR DESCRIPTION
**Pull request by dploeger**

### CODE REVIEW

**Comment by antelle** [comment]
Thanks! 🎁

File: app/scripts/models/app-model.js [hunk 1]
```diff
@@ -891,6 +892,16 @@ const AppModel = Backbone.Model.extend({
...
     },
 
+    unsetKeyFile: function (fileId) {
+        const fileInfo = this.fileInfos.get(fileId)
+        fileInfo.set({
+            keyFileName: null,
+            keyFilePath: null,
+            keyFileHash: null
+        });
+        this.fileInfos.save()
```
Comment (antelle) [inline app/scripts/models/app-model.js]: Please add commas. I'll fix this one, since it's already merged.
